"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var template_loader_1 = require("./loaders/template-loader");
var component_1 = require("./decorators/component");
exports.Component = component_1.Component;
var prop_1 = require("./decorators/prop");
exports.Prop = prop_1.Prop;
var watch_1 = require("./decorators/watch");
exports.Watch = watch_1.Watch;
var method_1 = require("./decorators/method");
exports.Method = method_1.Method;
exports.default = template_loader_1.TemplateLoader;
